### ISSUE TITLE
How exactly do I use this?

### ISSUE THREAD

**Issue by DeltaD36** [tmedwards/CoCEd#13]
Has something with this recent version changed in that it no longer uses a .exe to work now?

I've 'downloaded' - at least I think I did correctly - the newest version  from the green box, and saved it as a .zip file.
The .zip file being named CoCEd-master.zip, which I extracted, expecting to see a .exe. To my surprise there was not one. 
Am I a stupid idiot and downloaded it incorrectly and/or just haven't found the .exe yet, or is this entirely different an requires a different method of editing?

**Comment by tmedwards** [comment]
> Am I a stupid idiot and downloaded it incorrectly […]

Magic :8ball: says: Yes.

You want to go to the [Releases page](https://github.com/tmedwards/CoCEd/releases) (linked near the top of the main page) and choose a release, or go directly to the [latest release](https://github.com/tmedwards/CoCEd/releases/latest), and download the file named `CoCEd-{version}.zip` (e.g. `CoCEd-1.3.1.zip`).
