### ISSUE TITLE
so down CoCEd-1.3.1 

### ISSUE THREAD

**Issue by JynxZox** [tmedwards/CoCEd#16]
Microsoft Security Essentials finds Trojan: Win32/Fethar.B!cl in the CoCEd.exe and quarantines it just thought i let you all know

**Comment by tmedwards** [comment]
Duplicate of issue #15.

**Comment by tmedwards** [comment]
Might as well post this here too.

Seeing that it's probably a MSE definition issue, I've submitted a complaint with Microsoft contesting MSE's classification of CoCEd.  We'll see where that goes.
