### ISSUE TITLE
Can't open COCEd. Crashes every time I try to open it.

### ISSUE THREAD

**Issue by ReilerTheDragonknight** [tmedwards/CoCEd#17]
I tried rebooting, redownloading, and even use GiveMePower (It started, but immediately closed.)
It keeps crashing, and I don't know what's causing it. I have no COCEd folder in Appdata\Local.
Here's the log.

Nome do Evento de Problema:	CLR20r3
  Assinatura do Problema 01:	CoCEd.exe
  Assinatura do Problema 02:	1.2.17.0 
  Assinatura do Problema 03:	55c260eb
  Assinatura do Problema 04:	PresentationCore
  Assinatura do Problema 05:	4.6.1055.0 
  Assinatura do Problema 06:	563c1cb8
  Assinatura do Problema 07:	bfc 
  Assinatura do Problema 08:	a
  Assinatura do Problema 09:	System.NullReferenceException (Most likely what's causing it.)
  Versão do SO:	6.1.7601.2.1.0.768.3
  ID de Região:	2057
  Informações Adicionais 1:	aede
  Informações Adicionais 2:	aede1009fee73ab1b155c797cab9e7e2
  Informações Adicionais 3:	0fbf
  Informações Adicionais 4:	0fbf5a29a702321c67f59ab704dfa6f4

Sorry if it's in portuguese...
I have .NET Framework 4 installed, and I run on Win7 64 bits. I use the Revamp Mod. Thanks for reading.

**Comment by tmedwards** [comment]
> Nome do Evento de Problema: CLR20r3

That seems to suggest that the Common Language Runtime version 2.0 is being used—used by .NET versions 2.0–3.5.  In contrast, .NET 4 uses the Common Language Runtime version 4.  So, if you're sure that you have .NET 4 installed, it seems that something is wrong with your install.

You should probably give the Microsoft .NET Framework Repair Tool a try:
https://www.microsoft.com/en-us/download/details.aspx?id=30135
