### ISSUE TITLE
Missing weapon: Dragon Shell Shield

### ISSUE THREAD

**Issue by ambjoorn94** [tmedwards/CoCEd#2]
I noticed that I can't find the weapon "Dragon Shell Shield" anywhere.
I'm not familiar enough with CoCEd's code to insert it myself.
The item code for the dragon shell shield is: DRGNSHL

**Comment by tmedwards** [comment]
That's probably because it's not a weapon.  Try looking under Shields.

It's been in the Revamp-Mod's data file since CoCEd 1.2.15.

**Comment by ambjoorn94** [comment]
I only mentioned it because I saw source code for it in vanilla.
I haven't tried the Revamp-Mod yet.

**Comment by tmedwards** [comment]
Vanilla?  Let me check….  Indeed it is.  /sigh

Thanks for the report.  It'll be in the next release.

**Comment by tmedwards** [comment]
Fixed by 7d2f3c3aea8a94c75eda5912b9649b16f127ebea.
