### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Coolmira12** [tmedwards/CoCEd#24]
[CoCEd: 1.3.1.28497, CoC Data: 1.0.2_mod_1.4.16b]
System.NullReferenceException: Objektreferanse er ikke satt til en objektforekomst.
   ved CoCEd.ViewModel.GameVM.UpdateChest() i C:\Users\tmedwards\Documents\Visual Studio 2015\Projects\CoCEd\CoCEd\ViewModel\GameVM.Core.cs:linje 239
   ved CoCEd.ViewModel.GameVM..ctor(AmfFile file, GameVM previousVM, Boolean isRevampMod) i C:\Users\tmedwards\Documents\Visual Studio 2015\Projects\CoCEd\CoCEd\ViewModel\GameVM.cs:linje 135
   ved CoCEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup) i C:\Users\tmedwards\Documents\Visual Studio 2015\Projects\CoCEd\CoCEd\ViewModel\VM.cs:linje 125
   ved System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   ved System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   ved System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   ved System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ved System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) what does this mean

**Comment by tmedwards** [comment]
See if the [latest release (v1.3.2)](https://github.com/tmedwards/CoCEd/releases/latest) resolves the issue.

**Comment by Coolmira12** [comment]
![Uten navn](https://user-images.githubusercontent.com/46031351/59690453-c3ca6080-91e1-11e9-9f36-af35af35dfd7.png)
so a new problem hope i am not anoying

**Comment by tmedwards** [comment]
CoCEd does not come with a Xianxia data file.  Copy your old one, or a new one, into the directory.

**Comment by Coolmira12** [comment]
it works now thx
