### ISSUE TITLE
Win 10 - It doesn't open

### ISSUE THREAD

**Issue by cursedfox** [tmedwards/CoCEd#5]
When I try to open the CocEd it does nothing. Doesn't even show an error message it's like I didn't even tried to open it. What could possibly be the problem? D:

**Comment by ambjoorn94** [comment]
Good thing I haven't updated yet

**Comment by tmedwards** [comment]
It works perfectly fine in Windows 10 (I'm running Windows 10), so that's not the issue.

Did you read and follow [the Requirements and Installation sections of the README](https://github.com/tmedwards/CoCEd/blob/master/README.md "https://github.com/tmedwards/CoCEd/blob/master/README.md")?

**Comment by cursedfox** [comment]
Yes, I read. I already have the .NET installed

**Comment by cursedfox** [comment]
I formated the computer and it's working now. You can close it :)

**Comment by tmedwards** [comment]
Done.
